"""add social links columns

Revision ID: 6438ad19d6f0
Revises: 5e198dd6ef12
Create Date: 2026-01-10 01:22:52.372806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6438ad19d6f0'
down_revision: Union[str, Sequence[str], None] = '5e198dd6ef12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.String(length=2048), nullable=True))
    op.add_column('users', sa.Column('website', sa.String(length=2048), nullable=True))
    op.add_column('users', sa.Column('github', sa.String(length=2048), nullable=True))
    op.add_column('users', sa.Column('gitlab', sa.String(length=2048), nullable=True))
    op.add_column('users', sa.Column('linkedin', sa.String(length=2048), nullable=True))
    op.add_column('users', sa.Column('discord', sa.String(length=2048), nullable=True))
    op.add_column('users', sa.Column('mail', sa.String(length=2048), nullable=True))
    op.alter_column('users', 'bio',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_column('users', 'profile')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.alter_column('users', 'bio',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               existing_nullable=True)
    op.drop_column('users', 'mail')
    op.drop_column('users', 'discord')
    op.drop_column('users', 'linkedin')
    op.drop_column('users', 'gitlab')
    op.drop_column('users', 'github')
    op.drop_column('users', 'website')
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###
