"""add post metadata and images

Revision ID: 9792e1fb44ac
Revises: 6438ad19d6f0
Create Date: 2026-03-11 17:13:32.414255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9792e1fb44ac'
down_revision: Union[str, Sequence[str], None] = '6438ad19d6f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_id'), 'images', ['id'], unique=False)
    op.create_index(op.f('ix_images_post_id'), 'images', ['post_id'], unique=False)
    op.add_column('posts', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('posts', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('posts', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('posts', sa.Column('image', sa.String(length=2048), nullable=True))
    op.add_column('posts', sa.Column('content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'content')
    op.drop_column('posts', 'image')
    op.drop_column('posts', 'tags')
    op.drop_column('posts', 'description')
    op.drop_column('posts', 'title')
    op.drop_index(op.f('ix_images_post_id'), table_name='images')
    op.drop_index(op.f('ix_images_id'), table_name='images')
    op.drop_table('images')
    # ### end Alembic commands ###
